name: CI and Publish package to the Maven Central Repository

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -V -B assemble
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: drop
          path: target/