name: Publish package to the Maven Central Repository

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: |
          mvn --batch-mode deploy
        env:
          SIGN_KEY: ${{ secrets.GPG_SECRET_KEY }}
          SIGN_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          SIGN_KEY_PASS: ${{ secrets.GPG_PASSPHRASE }}
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
